import base64, datetime


def run(config: dict, result_text: str, query: str, user_params: dict) -> dict:
    try:
        from fpdf import FPDF
    except ImportError:
        raise RuntimeError("fpdf2 is not installed — run: pip install fpdf2")

    title    = user_params.get("title") or f"Knowledge Base Report — {datetime.date.today()}"
    filename = f"report_{datetime.date.today()}.pdf"

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.multi_cell(0, 10, title)
    pdf.ln(4)

    # Query
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Query", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, query)
    pdf.ln(5)

    # Result
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Result", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, result_text)

    # Footer
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 6, f"Generated by Huron GenAI — {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}")

    pdf_bytes = pdf.output()
    return {
        "detail":         "PDF generated",
        "filename":       filename,
        "content_base64": base64.b64encode(pdf_bytes).decode(),
    }
